# Generated by IBM TransformationAdvisor
# Fri Nov 08 08:18:11 GMT 2019


FROM  docker-registry:5000/adoptopenjdk/openjdk8-openj9:v9 as builder
COPY . /project

RUN cd /project/target
WORKDIR /project/target

RUN mkdir /config/dropins
COPY tradelite.war /config/dropins

FROM open-liberty:kernel-java8-openj9

COPY --chown=1000060000:0 --from=builder /config/ /opt/ol/wlp/usr/servers/defaultServer
EXPOSE 9443
