#Deploy the pod
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: daytrader
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: daytrader
    spec:
      containers:
      - env:
        - name: WLP_OUTPUT_DIR
          value: /opt/ol/wlp/output/defaultServer
        name: daytrader
        ports:
        - containerPort: 9080
        imagePullPolicy: Always
---
#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: daytrader-service
  annotations:
    debliberty: "true"
  labels:
    app: daytrader
spec:
  type: NodePort
  ports:
    - nodePort: 31214
      name: http
      port: 9080
      protocol: TCP
      targetPort: 9080
  selector:
    app: daytrader
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: daytrader
spec:
  host: daytrader.ocp.ibm.com
  path: /trader
  to:
    kind: Service
    name: daytrader-service
    weight: 100
  wildcardPolicy: None
status:
  ingress: null


