#Deploy the pod
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: daytrader
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: daytrader
    spec:
      containers:
      - env:
        - name: WLP_OUTPUT_DIR
          value: /opt/ol/wlp/output/defaultServer
        name: daytrader
        ports:
        - containerPort: 9443
        imagePullPolicy: Always
---
#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: daytrader-service
  annotations:
    debliberty: "true"
  labels:
    app: daytrader
spec:
  type: NodePort
  ports:
    - nodePort: 31214
      name: https
      port: 9443
      protocol: TCP
      targetPort: 9443
  selector:
    app: daytrader
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"route.openshift.io/v1","kind":"Route","metadata":{"annotations":{},"name":"daytrader","namespace":"tekton"},"spec":{"host":"daytrader.ocp.ibm.com","tls":{"insecureEdgeTerminationPolicy":"Redirect","termination":"Reencrypt"},"to":{"kind":"Service","name":"day-trader-service"}}}
  creationTimestamp: null
  name: icpa-landing
  selfLink: /apis/route.openshift.io/v1/namespaces/kabanero/routes/icpa-landing
spec:
  host: daytrader.ocp.ibm.com
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: daytrader-service
    weight: 100
  wildcardPolicy: None
status:
  ingress: null


